apiVersion: v1
kind: Service
metadata:
 name: myapp-service
spec:
 types: NodePort     # Can be LoadBalancer/NodePort - Default is ClusterIP
 ports:
 - targetPort: 80
   port: 80
   nodePort: 30008
 selector:              # It is used to connect service to the pods
   app: myapp
   type: front-end
