apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    requests.ephemeral-storage: 8Gi    
    limits.ephemeral-storage: 10Gi
    limits.cpu: "10"
    limits.memory: 10Gi
